unstable_features = true
imports_granularity = "crate"
max_width = 120
comment_width = 100  # make sure examples in docs fit when rendered
wrap_comments = true
format_code_in_doc_comments = true
format_macro_bodies = true
format_macro_matchers = true
normalize_comments = true
normalize_doc_attributes = true
use_field_init_shorthand = true
version = "Two"