[package]
name = "iota-streams"
version = "0.1.0"
authors = ["Vlad Semenov <vlad.semenov@iota.org>"]
edition = "2018"
license = "Apache-2.0/MIT"
readme = "README.md"
keywords = ["iota", "streams"]
description = "A rust implementation of the IOTA Streams"

[lib]
name = "iota_streams"

[workspace]
members = [
    "iota-streams-core",
    "iota-streams-core-keccak",
    "iota-streams-core-ntru",
    "iota-streams-core-merkletree",
    "iota-streams-core-mss",
    "iota-streams-protobuf3",
    "iota-streams-app",
    "iota-streams-app-channel",
]

[dependencies]
iota-streams-core = { version = "0.1.0", path = "iota-streams-core" }
iota-streams-core-keccak = { version = "0.1.0", path = "iota-streams-core-keccak" }
iota-streams-core-ntru = { version = "0.1.0", path = "iota-streams-core-ntru" }
iota-streams-core-merkletree = { version = "0.1.0", path = "iota-streams-core-merkletree" }
iota-streams-core-mss = { version = "0.1.0", path = "iota-streams-core-mss" }
iota-streams-protobuf3 = { version = "0.1.0", path = "iota-streams-protobuf3" }
iota-streams-app = { version = "0.1.0", path = "iota-streams-app" }
iota-streams-app-channel = { version = "0.1.0", path = "iota-streams-app-channel" }
