#cargo-features = ["named-profiles"]

[package]
name = "iota-streams"
version = "1.1.0"
authors = ["Vlad Semenov <vlad.semenov@iota.org>", "Dyrell Chapman <dyrell.chapman@iota.org>", "Brord van Wierst <brord@iota.org>"]
edition = "2018"
license = "Apache-2.0/MIT"
readme = "README.md"
keywords = ["iota", "streams"]
description = "A rust implementation of the IOTA Streams"
autoexamples = false

[lib]
name = "iota_streams"
crate-type = ["staticlib", "cdylib", "rlib"]

[workspace]
members = [
    "iota-streams-core",
    "iota-streams-core-edsig",
    "iota-streams-core-keccak",
    "iota-streams-ddml",
    "iota-streams-app",
    "iota-streams-app-channels",
    "iota-streams-app-channels-example",
    #"iota-streams-app-channels-js",
    "bindings/wasm",
]
exclude = [
    "bindings/c",
    "examples",
    # "bindings/wasm",
]

[features]
default = ["std", "tangle", "sync-client"]
# Enable `std` feature in dependencies
std = ["iota-streams-core/std", "iota-streams-core-edsig/std", "iota-streams-ddml/std", "iota-streams-app/std", "iota-streams-app-channels/std"]
async = ["iota-streams-app/async", "iota-streams-app-channels/async"]
tangle = ["iota-streams-app/tangle", "iota-streams-app-channels/tangle"]
sync-client = ["iota-streams-app/sync-client", "iota-streams-app-channels/sync-client"]
async-client = ["iota-streams-app/async-client", "iota-streams-app-channels/async-client"]
wasm-client = ["iota-streams-app/wasm-client", "iota-streams-app-channels/wasm-client"]
err-location-log = ["iota-streams-core/err-location-log"]

[dependencies]
iota-streams-core = { version = "0.3.0", path = "iota-streams-core", default-features = false }
iota-streams-core-keccak = { version = "0.3.0", path = "iota-streams-core-keccak", default-features = false }
iota-streams-core-edsig = { version = "0.2.0", path = "iota-streams-core-edsig", default-features = false }
iota-streams-ddml = { version = "0.2.2", path = "iota-streams-ddml", default-features = false }
iota-streams-app = { version = "1.1.0", path = "iota-streams-app", default-features = false }
iota-streams-app-channels = { version = "1.1.0", path = "iota-streams-app-channels", default-features = false }

#[profile.release-nostd]
#inherits = "release"
#opt-level = 's'
#debug = false
#rpath = false
#lto = true
#debug-assertions = false
#codegen-units = 1
#panic = "abort"

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"
lto = true
#panic = 'abort'
