[package]
name = "iota_streams_wasm"
version = "0.0.1"
authors = ["Team IOTA Streams"]
edition = "2018"
repository = "https://github.com/iotaledger/streams"
homepage = "https://www.iota.org"
license = "MIT"

[lib]
crate-type = ["cdylib"]

# TODO: Discover this:
[package.metadata.wasm-pack.profile.release]
wasm-opt = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasm-bindgen = { version = "0.2", features = ["serde-serialize"] }
wasm-bindgen-futures = "0.4.19"
console_error_panic_hook = "0.1.6"
js-sys = "0.3.46"

serde = { version = "1.0", features = ["derive"] }

iota-streams = {path = "../../", default-features = false, features = ["tangle", "wasm-client", "async"]}#
